### ISSUE TITLE
Mercs seem to spawn at an insane rate in Biomes You'll Go's Glowing Ancient Forest Biome

### ISSUE THREAD

**Issue by verbina29** [cybercat-mods/HWG#10]
I've actually already turned down the spawn weight to 1, and they spawn far less in other biomes. In BYG's Glowing Ancient Forest, they seem to spawn at an absolutely insane rate. There were definitely at least 20 of them.

**Comment by AzureDoom** [comment]
This is a BYG issue not ours, this has been noticed before and it's 100% on them as vanilla is fine
