### ISSUE TITLE
Forge 1.20.1 doesn't seem to work

### ISSUE THREAD

**Issue by BlazingDrake75** [cybercat-mods/HWG#101]
I get no error, or crash, it just doesn't load. I've looked at a few other issues, but I can't find one that fits with this issue.
![dtnm,dyytjs](https://github.com/cybercat-mods/HWG/assets/102114300/bfefa2d0-065e-4f8d-a121-cb510bb8d348)
![fynntyrrtyhntyn](https://github.com/cybercat-mods/HWG/assets/102114300/90eee9c3-fa24-4ba7-9800-113ea29d1070)

**Comment by AzureDoom** [comment]
![image](https://github.com/cybercat-mods/HWG/assets/7415711/85810db4-3948-4b3d-8dcb-459b3ff5a63c)
Please see the required mods but that version of SBL and Forge will not work.

**Comment by BlazingDrake75** [comment]
Woah, where does it tell you the required mods? Also great response time lol

**Comment by ikrase** [comment]
I am also having difficulty related to getting the right dependencies, though for me it launches but then crashes if a merc exists in the world.
