### ISSUE TITLE
Inifite ammo and shotguns cannot reload

### ISSUE THREAD

**Issue by ghost** [cybercat-mods/HWG#102]
Pistols, snipers, and shotguns cannot be reloaded. The automatics have infinite ammo, they will not run out of bullets. I press R to reload and it does not work for pistols and shotguns, I've also tried changing my key binds.

**Comment by AzureDoom** [comment]
Going to need a lot more info like game version, mod version, other mods you may be using, etc. Please create an issue with the proper info.
