### ISSUE TITLE
Tommy Gun and Grenade Launcher Freeze

### ISSUE THREAD

**Issue by TheRebelT** [cybercat-mods/HWG#103]
fabric-loader-0.14.22-1.20.1
Modlist:
![image](https://github.com/cybercat-mods/HWG/assets/40326233/55862d6b-347b-4109-b2aa-cda782993711)

Tommy Gun cooldown seems to ignore the numbers the config is set to and shoots as quickly as it would by default. Other guns all seem to be fine with this, though I haven't tested all of them just yet.

When testing out the grenade launcher, it reloaded with no sound effect (shotgun didn't have one either, despite there being sound files for it. I thought it was intentional so I didn't report it) but when trying to fire the grenade launcher, the game froze. After a couple of minutes I closed the game as it wasn't unfreezing which inevitably made it crash (kinda forced it too) but I'm still wondering if the report has anything useful regarding that bug:
https://pastebin.com/BZxD90P4 - Crash Log
I've also pastebined the latest log as well
 https://pastebin.com/TyCRKtQe - Latest Log
 
 Edit: It appears to just be the tommy gun and the balrog that has the cooldown issue, and the brimstone seems to behave funny when you change it's ammo capacity (like changing it to 5 and shooting it once sets it to -4/5). But otherwise all the other guns seem to be fine with any config changes. And I have managed to do the grenade launcher freeze several times now, so I am confident that it's not a 1 off. It also puts me back in time but I feel like that's just Minecraft reverting the world and player back to a safe spot when the crash didn't occur.

**Comment by AzureDoom** [comment]
Fixed in a new release.
