### ISSUE TITLE
Forge 1.20.1 error loading

### ISSUE THREAD

**Issue by purplepumpkin09182** [cybercat-mods/HWG#104]
Clean profile on curseforge launcher with everything it auto downloads (forge version 47.2.0)

![image](https://github.com/cybercat-mods/HWG/assets/139901190/849ba80b-dd96-4974-984b-0fd1d6b4f141)

Get this error message (despite having that fabric api in the folder)

![image](https://github.com/cybercat-mods/HWG/assets/139901190/9ebd5b3b-fe76-4525-8de2-a36790669223)

[crash-2023-11-09_23.55.41-fml.txt](https://github.com/cybercat-mods/HWG/files/13315734/crash-2023-11-09_23.55.41-fml.txt)

Remove and re-add fabric manually. Get this error instead

![image](https://github.com/cybercat-mods/HWG/assets/139901190/85079961-ea02-4f01-a5ad-2ad452e09f8f)

[crash-2023-11-10_00.04.00-fml.txt](https://github.com/cybercat-mods/HWG/files/13315724/crash-2023-11-10_00.04.00-fml.txt)

So I change the forge version to 47.1.3

![image](https://github.com/cybercat-mods/HWG/assets/139901190/04eb5db2-6244-4319-ad56-9e181bd7af62)

[crash-2023-11-10_00.08.59-fml.txt](https://github.com/cybercat-mods/HWG/files/13315762/crash-2023-11-10_00.08.59-fml.txt)

so uh yeah. not sure what im doing wrong here.

**Comment by purplepumpkin09182** [comment]
now that i think about it, im getting screwed over by curseforge's auto installs aren't I

**Comment by AzureDoom** [comment]
The latest one is the most correct, you just have to use the SBL marked as neo, not forge, per it's changelog on the latest file. This is an issue with SBL on CurseForge.

**Comment by purplepumpkin09182** [comment]
Ahh. I missed that. Thank you very much.
