### ISSUE TITLE
Inifite ammo and shotguns cannot reload (More Info)

### ISSUE THREAD

**Issue by ghost** [cybercat-mods/HWG#105]
Going to need a lot more info like game version, mod version, other mods you may be using, etc. Please create an issue with the proper info.

_Originally posted by @AzureDoom in https://github.com/cybercat-mods/HWG/issues/102#issuecomment-1803878325_

Game Version: 1.20.1 FORGE
mod version: HWGMod-connector-1.20.1-1.4.22.jar
Other mods that are interfering with the reload key bind (however I have tried changing the key bind to something completely new and it still didn't work which is odd): Iron's Spells 'n Spellbooks

**Comment by AzureDoom** [comment]
Please try with out Iron's Speels 'n Spellbooks as it works normally for me.

**Comment by ghost** [comment]
> Please try with out Iron's Speels 'n Spellbooks as it works normally for me.

Still does not work

**Comment by AzureDoom** [comment]
https://streamable.com/romofq

Everything is working for me just fine on the latest version of everything and even with shaders.
