### ISSUE TITLE
HWG Connector

### ISSUE THREAD

**Issue by zorex73** [cybercat-mods/HWG#107]
It could be me just missing something but whenever I try to use the forge version of HWG it fails, I've tried with the dependencies and without(dependencies, AzureLib, Forgified Fabric API, SmartBrainLib, Sinytra Connector) However forge just gives me a 43 item list of missing dependencies that are all related to fabric api.

**Comment by AzureDoom** [comment]
Downgrade the FFAPI

**Comment by zorex73** [comment]
what version should I downgrade too? I tried a couple.

**Comment by zorex73** [comment]
If I have any version above 0.86.0 it says 43 errors, but any lower and it says i'm missing fabric

**Comment by zorex73** [comment]
Hi
