### ISSUE TITLE
HWG causes crash when used with Haema/Bewitchment

### ISSUE THREAD

**Issue by noclueumbreon** [cybercat-mods/HWG#11]
Using a silver weapon on someone transformed into a vampire from Haema crashes the game. Will update with crash logs when I can test further, but the process to replicate should be roughly this:

1. Install fabric, as well as HWG, Haema, Bewitchment, and all the libraries for each.
2. With a friend who has used a vampire blood injector, shoot them with a weapon which fires silver bullets.
3. Crash

Thanks

**Comment by AzureDoom** [comment]
I will need logs

**Comment by AzureDoom** [comment]
No log provided, issue is now closed
