### ISSUE TITLE
Client Disconnect

### ISSUE THREAD

**Issue by NickMesser** [cybercat-mods/HWG#114]
Its taboo but I am making a forge pack around zombie survival and I am using this mod as the core gun mod. 

Everything works great except sometime there is a random disconnect with this error in the console. 

https://mclo.gs/HkiOE3d#L928

This might be a syntra issue and if it is let me know and Ill pass the error to them! Thanks!

**Comment by AzureDoom** [comment]
All Forge reports must be sent to Syntra for this as this does not happen with the Fabric version.
