### ISSUE TITLE
[Suggestion] Polishing illager shooters' animation

### ISSUE THREAD

**Issue by betterworld-sjq** [cybercat-mods/HWG#117]
It feels weird that illagers raise their guns for a second to shoot you and then put it down, and repeat up-and-down performance. Could you make it that they would always be raising their guns when they found the target, and make those who carry big guns (like shotguns and ak47s etc) hold their weapons with both arms (like pillagers holding crossbows)

**Comment by AzureDoom** [comment]
Outside of scope currently.
