### ISSUE TITLE
Question: Rotating models

### ISSUE THREAD

**Issue by cec1Ie** [cybercat-mods/HWG#118]
Hey, I'm trying to figure out how to rotate the models to make them look correct in Vivecraft, but importing the json files into blockbench tells me there's no actual model in the json files. What am I doing wrong?

**Comment by TheRebelT** [comment]
The .json models are just for the display settings (how it appears in the hand). The model is in the .geo.json file as HWG uses Azurelib

If you're changing the position of the model, you're editing the right file, but it'll be trial an error with making changes, going back into the game and F3+T to refresh resources and see how much changed, what possible tweaks you'll need to make, etc.

**Comment by cec1Ie** [comment]
I'll try that, thank you!!

**Comment by cec1Ie** [comment]
> The .json models are just for the display settings (how it appears in the hand). The model is in the .geo.json file as HWG uses Azurelib
> 
> If you're changing the position of the model, you're editing the right file, but it'll be trial an error with making changes, going back into the game and F3+T to refresh resources and see how much changed, what possible tweaks you'll need to make, etc.

Unfortunately, although I am able to change the model's position, the rotation variables don't actually seem to do anything
