### ISSUE TITLE
Using guns causes crash

### ISSUE THREAD

**Issue by SunsetJesus4653** [cybercat-mods/HWG#119]
Using guns will eventually cause an error that kicks me to the main menu. The error is: "Internal Exception: java.util.ConcurrentModificationException". It happens after a few seconds of firing. I cannot figure out what the issue is. I am using this mod in a custom modpack with quite a few mods, but none of them should be conflicting with this mod. If needed, I can send a list of all mods, but hopefully a solution to this issue is already known and that won't be necessary lol.

**Comment by AzureDoom** [comment]
Please test with just the mod itself.

**Comment by BowBoy1** [comment]
I am having the same issue. Not sure if it's related to the fact I'm using it on Forge with the Sinytra Connector mod.

**Comment by BowBoy1** [comment]
The weirdest part is that it doesn't happen consistently, it's seemingly random.

**Comment by BowBoy1** [comment]
Confirmed that it happens on its own on both Fabric and Forge.

**Comment by rylarolls** [comment]
Installed via modrinth launcher on a fresh pack with dependencies as well, fabric 1.20.4. Right clicking causes a crash to desktop.
[crash-2024-03-03_19.46.48-server.txt](https://github.com/cybercat-mods/HWG/files/14474354/crash-2024-03-03_19.46.48-server.txt)

**Comment by Nate4Fate** [comment]
Same thing happens in 1.20.1

**Comment by jwaxy** [comment]
getting same error as rylarolls

**Comment by FRTI64** [comment]
[crash-2024-03-09_23.21.41-server.txt](https://github.com/cybercat-mods/HWG/files/14546753/crash-2024-03-09_23.21.41-server.txt)

**Comment by Syclusion** [comment]
its c2me https://github.com/RelativityMC/C2ME-fabric/issues/278#issuecomment-1987118277

**Comment by lnee94** [comment]
> its c2me [RelativityMC/C2ME-fabric#278 (comment)](https://github.com/RelativityMC/C2ME-fabric/issues/278#issuecomment-1987118277)

What does that mean?

**Comment by Syclusion** [comment]
> > its c2me [RelativityMC/C2ME-fabric#278 (comment)](https://github.com/RelativityMC/C2ME-fabric/issues/278#issuecomment-1987118277)
> 
> What does that mean?

Means if you have c2me remove it. And the crash stops

**Comment by AzureDoom** [comment]
Closing in this case.
