### ISSUE TITLE
2 issues in one

### ISSUE THREAD

**Issue by TheNimbleNinja** [cybercat-mods/HWG#12]
plz add a link to your issue page via the mod page i didnt know this existed and the mod causes the game to crash when you try to craft a plank https://gist.github.com/TheNimbleNinja/e4e19a1882f53f376339208f97b0d25c

**Comment by AzureDoom** [comment]
This is an issue with NBT Crafting https://github.com/Siphalor/nbt-crafting/issues/78 which is a library we include. Fix should be released from Spihalor, pulling and testing now.

**Comment by TheNimbleNinja** [comment]
okay thanks for the quick response :) i was sad i had to remove this mod

**Comment by AzureDoom** [comment]
I'll have an update out with the updated library in about 5 minutes
