### ISSUE TITLE
HWG crash after shot

### ISSUE THREAD

**Issue by Romans96** [cybercat-mods/HWG#121]
Hello! I've discovered that HWG with my modpack crashes each time i shoot.
But i cannot find which mod causes this.
I've reported 2 errors:
Async Entity Error (instantly after shooting 1 projectile):
https://pastebin.com/8wbQ5SiZ

NullPointer Error (some seconds after shooting 1 projectile):
https://bytebin.lucko.me/0cAzbv9ZZ8

**Comment by Syclusion** [comment]
it is c2me https://github.com/RelativityMC/C2ME-fabric/issues/278#issuecomment-1987118277
