### ISSUE TITLE
World (Not client) Crashes after shooting

### ISSUE THREAD

**Issue by agent14bricks** [cybercat-mods/HWG#122]
In a singleplayer world in my modpack, I end up getting some crashes. I don't know what would cause the incompatibility in this case. I don't have C2ME installed, and the Immersive portals errors happened before the crash and not during it. The client stays open but it says "Connection Lost" with "Internal Exception: java.util.ConcurrentModificationException"

[null[221611] [mainINFO] Loading Min.txt](https://github.com/cybercat-mods/HWG/files/14681443/null.221611.mainINFO.Loading.Min.txt)

It is over 300 mods, however it is stable outside of when I added this mod, but it seems to only happen when shooting _Sometimes_. Help is appreciated

**Comment by agent14bricks** [comment]
Upon some further testing:
- Opening world to LAN causes the crash to become less frequent
- It is a softcrash, meaning every position and inventory saves before closing the world
- Redirects to Serverlist even when it was a singleplayer crash
- most commonly happens when mob is shot in the torso from eye level, or in the head from way above

**Comment by AzureDoom** [comment]
Please test with latest.
