### ISSUE TITLE
spawn weight has no effect

### ISSUE THREAD

**Issue by ale1str** [cybercat-mods/HWG#124]
I wanted the techno demons gone so i changed all of their settings to 0. still lost a hardcore world to a techno demon. i double checked all of the settings right before i died: spawn weight, max group, for lesser and greater techno demon. don't want to seem like an ass or anything but i am switching mc versions to use simple animated guns. hope this issue can be fixed for the next person because i really enjoyed the mod up to this point. thanks for all your work. i was on version 1.19.4 fabric.

**Comment by AzureDoom** [comment]
1.19.4 is unsupported and does not receive updates.
