### ISSUE TITLE
[BUG] Sniper Rifle Does Not Reload In Survival

### ISSUE THREAD

**Issue by Knewest** [cybercat-mods/HWG#125]
### Version: 
hwg-fabric-1.20 2.0.2

### What Happened:
In survival, when you initially get the sniper rifle from a spy drop, you can reload it, but after firing two shots, you will be unable to reload the rifle, effectively making it (and the bullets you used diamonds to craft) useless. I noticed that the durability is set to 0/3 when initially dropped, which is when I can reload, but after that, it is always at 2/3 (which seems to align with other guns), but I cannot reload.

### Note:
I attempted to get my friends to reload it for me, but they also couldn't.

### Modrinth Log (Doesn't Seem To Show Anything Relevant):
https://mclo.gs/hy9hbF7

**Comment by Knewest** [comment]
Changing the sniper config settings to have 1 capacity allows me to reload, but using regular bullets, seemingly making sniper bullets have absolutely zero usage, and the sniper now shoots 9mm parabellum bullets.

**Comment by benio1394** [comment]
I also have this problem. Sniper rifle is only working with normal bullets.

**Comment by AzureDoom** [comment]
1.20.1 isn't being maintained anymore, please test with 1.20.4.
