### ISSUE TITLE
[BUG] Server Crashing upon another player being shot dead by an SMG.

### ISSUE THREAD

**Issue by tivvo** [cybercat-mods/HWG#126]
for context, friend shot another friend with a smg and they died
server crashed straight after death with a entity null crash
shrug, crash log here
[crash-2024-05-08_22.29.10-server.txt](https://github.com/cybercat-mods/HWG/files/15255653/crash-2024-05-08_22.29.10-server.txt)

**Comment by tivvo** [comment]
forgot to mention,
ver 2.0.2 on fabric, 1.20.1.

**Comment by AzureDoom** [comment]
1.20.1 is no longer maintained.
