### ISSUE TITLE
How to change spawn biomes 

### ISSUE THREAD

**Issue by GamerTable** [cybercat-mods/HWG#129]
I'm on Fabric 1.20.1 latest version of mod and I can't find the config to change spawn biomes
![image](https://github.com/cybercat-mods/HWG/assets/114619268/17a984e7-f96b-43b3-8c4f-ac1632679686)

**Comment by AzureDoom** [comment]
That is because its a data pack thing, not config file https://github.com/cybercat-mods/HWG/tree/1.20/src/main/resources/data/hwg/tags/worldgen/biome

**Comment by GamerTable** [comment]
Ty
