### ISSUE TITLE
HWG version 2.2.0, fabric, 1.20.6, unable to reload any gun

### ISSUE THREAD

**Issue by spaghettilmfao** [cybercat-mods/HWG#132]
I have the ammo the tooltips tell me to use, I've pressed every button possible. I've looked on the mod page and at other people's, found nothing. Maybe it has something to do with the fact that I installed it and opened a previously generated world?

**Comment by AzureDoom** [comment]
Just tested, can verify all weapons are reloading fine for me. Check your keybinds.
