### ISSUE TITLE
AzureLib error

### ISSUE THREAD

**Issue by Harplight** [cybercat-mods/HWG#134]
Trying to put this mod on a server, came back with this:
"Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (azurelib:anim_trigger_sync)"

Can't find anything online on how to fix this.

Edit: Forgot to mention it's version 1.20.6 (Fabric).
No C2ME mod and I double checked the version is compatible.

**Comment by AzureDoom** [comment]
Update to Azurelib 2.2.12
