### ISSUE TITLE
Gun Table does not work; Unable to craft

### ISSUE THREAD

**Issue by Ujjwal-Rohilla** [cybercat-mods/HWG#135]
Running on Minecraft Server Fabric 1.20.6 (on Aternos), Mod version 2.2.0

Hi there,

When trying to craft bullets in the Gun Table, it does not work (nothing is given out)

Thanks,
Me.

**Comment by AzureDoom** [comment]
Please test on an a dedicated server, Aternos reports are not valid as Aternos is closed source trash.

**Comment by Ujjwal-Rohilla** [comment]
I don't have a dedicated server, but I did try it in singleplayer and I am able to craft bullets. Guess it is a problem with Aternos

Any help or advice though?

And uh here is the complete mod list in the server maybe that might help
![image](https://github.com/user-attachments/assets/f387068e-8c23-4c76-b4b1-5abf2d2eacb3)

Thanks and regards,
Me
