### ISSUE TITLE
Causing every world to crash in 1.20.6

### ISSUE THREAD

**Issue by ZorionTen** [cybercat-mods/HWG#138]
PFA error report:
[crash-2024-08-20_21.29.13-server.txt](https://github.com/user-attachments/files/16678553/crash-2024-08-20_21.29.13-server.txt)

More details:
![image](https://github.com/user-attachments/assets/1b179f92-f514-4425-8ca0-f58fe2eb019e)

There are a lot of other mods. Removing this mod fixes the crash. 
But some how my server with the exact same mods has not yet crashed. The only difference is that the server is on fabric and local is on quilt

**Comment by AzureDoom** [comment]
Issue sbl, not this.
