### ISSUE TITLE
crafting recipes pull up different weapons

### ISSUE THREAD

**Issue by dabsterflash** [cybercat-mods/HWG#139]
i have a list of mods im using as well as hwg, I go to craft an ak it works the first time i go to craft a tommy gun and it pulls up pistol and other sorts recipes that im not crafting and then it crashed my game and gave me a crash report that i unfortunately lost.

**Comment by AzureDoom** [comment]
No version stated for the mod or mc version and no log provided, yeah, closing as this has no info.
