### ISSUE TITLE
error loading silver recipes

### ISSUE THREAD

**Issue by matt31084** [cybercat-mods/HWG#14]
I would like to use this mod in my pack however I don't want to include bewitchment.  I do have industrial revolution in my pack which has a silver ore and ingots.  Could the mod be updated to look for silver ore from different mods?  It would be nice if I could eliminate the errors in my log file below.

https://pastebin.com/5v2JgWUD

**Comment by AzureDoom** [comment]
The guns themselves require code from Bewitchment and only register if Bewitchment is loaded therefore it would be pointless to do. Just gonna have to ignore the error in the log.
