### ISSUE TITLE
Game crashing on startup with mod installed

### ISSUE THREAD

**Issue by mcheezic05** [cybercat-mods/HWG#141]
**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: Fabric loader 0.16.7-1.21.1
Mod version: 3.0.1

**Describe the bug**
The game crashes on startup with this mod installed. Happens even if HWG, AzureLib, and Fabric API are the only mods installed. 
The error message is as follows.
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hwg' at 'mod.azure.hwg.FabricLibMod'!

**To Reproduce**
Start the game with the mod installed.

No screenshots, but here's the crash log if necessary.
[crash-2024-10-27_22.37.45-client.txt](https://github.com/user-attachments/files/17536677/crash-2024-10-27_22.37.45-client.txt)

**Comment by AzureDoom** [comment]
Properly read the requirements that are listed per file

**Comment by mcheezic05** [comment]
SBL is not listed as a requirement anywhere on the CurseForge page despite that page still being updated. I did properly read the requirements on the site I downloaded it from - the site did not properly list every requirement.

**Comment by AzureDoom** [comment]
Because sbl is not a requirement of 1.21.1 the requirements are properly stated per file as stated. Learn to read

**Comment by mcheezic05** [comment]
Take a wild guess as to where Common Network is listed as a dependency on the CurseForge page. If you guessed "nowhere," you'd be right.

**Comment by AzureDoom** [comment]
![image](https://github.com/user-attachments/assets/7246e800-f839-4e05-bc1a-1349dbea77a2)
So you just like being a dumbass?
