### ISSUE TITLE
[BUG] Crash with REI

### ISSUE THREAD

**Issue by lartts** [cybercat-mods/HWG#16]
Log:
[latest.log](https://github.com/AzureDoom/HWG/files/6706383/latest.log)

Crash Report:
[crash-2021-06-24_11.57.53-client.txt](https://github.com/AzureDoom/HWG/files/6706387/crash-2021-06-24_11.57.53-client.txt)

The version of Fabric that I am using is 0.11.6
The version of the HWG that I am using is 1.0.15
The version of REI that I am using is 5.12.248

Crashes when I try to type "@Happiness is a warm gun" in the REI search bar

**Comment by AzureDoom** [comment]
This isn't a HWG issue. This is an issue with REI and Geckolib, which REI has to fix.

**Comment by AzureDoom** [comment]
actually wrong issue, your issue is that you need to be looking at `@hwg`
