### ISSUE TITLE
crash on see your items in rei

### ISSUE THREAD

**Issue by TheNimbleNinja** [cybercat-mods/HWG#17]
https://gist.githubusercontent.com/natanfudge/8a01a474b80363d7f31f624ac559a482/raw/0dcf2e49c57f994112a6cb3e331ab6ffd96f397e/crash.txt

**Comment by AzureDoom** [comment]
No ETA on fix, will get to it when I can get to it.

**Comment by OdieHerpaderp** [comment]
Just chiming in to say i was able to reproduce the issue.

https://pastebin.com/KiEtegf5

Hopefully this helps in anyway :)

**Comment by AzureDoom** [comment]
Its already fixed, the code is just tore apart currently for the sfx update so I can't push the fix.
