### ISSUE TITLE
User is an idiot 

### ISSUE THREAD

**Issue by LordDecay26** [cybercat-mods/HWG#21]
https://pastebin.com/rV9X6RxM -- latest ""working"" version

https://pastebin.com/R8RxvSqj -- latest version full stop. - has been removed from Curseforge due to how broken it is.

dont be taking down my bug reports just because you dont like them, im not gonna fix your fuckin mod for you. idk why you bother publishing anything if it isnt gonna work. have a nice day man.

**Comment by LordDecay26** [comment]
>fixes a null item
>game crashes on startup instead


jermalaugh.gif

**Comment by AzureDoom** [comment]
That's a different issue fuck face but hey guess what, welcome to the ban list idiot.
