### ISSUE TITLE
version 1.17 crash

### ISSUE THREAD

**Issue by taiwan-king** [cybercat-mods/HWG#24]
[crash-2021-07-19_13.37.36-client.txt](https://github.com/AzureDoom/HWG/files/6838248/crash-2021-07-19_13.37.36-client.txt)

Previous test, there is found that Febric API is not using the latest version, so it will conflict with other mods.

Use alone works fine.

my test mods:
geckolib-fabric-1.17-3.0.8.jar
HWGMod-1.17-1.0.6.jar
fabric-api-0.36.0+1.17.jar
voicechat-1.17-1.1.4.jar

**Comment by AzureDoom** [comment]
1.17 isn't supported; use 1.17.1
