### ISSUE TITLE
Unknown recipe serializer?

### ISSUE THREAD

**Issue by L0rne** [cybercat-mods/HWG#25]
Error:
Internal Exception: io.netty.handler.codec.DecodeerException:java.lang.IllegalArgumentException: Unknown recipe serializer hwg:gun_table

This is a newly created Fabric 1.17.1 server

Mods:
HWGMOD-1.17-1.0.10
geckolib-fabric-1.17-3.0.10
fabric-api-0.37.0+1.17
floodgate-fabric
Geyser-Fabric-1.4.0-SNAPSHOT
lithium-fabric-mc1.17.1-0.7.3

I also tried HWG 1.0.9 and 1.0.8.

Any idea what could be causing this?

Thanks!

**Comment by AzureDoom** [comment]
Full log?

**Comment by L0rne** [comment]
I'm getting a different error now:

Connection Lost

Registry remapping failed: Received ID map for minecraft:particle_type contains IDs unknown to the receiver!
- hwg:pink_flare
- hwg:light_gray_flare
(etc)

Full log attached

[latest.log](https://github.com/AzureDoom/HWG/files/6871721/latest.log)

**Comment by AzureDoom** [comment]
Please try without Geyser

**Comment by L0rne** [comment]
Nevermind, I'm dumb.  I didn't have HWG installed in my client.

Thanks for the help!
