### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shiplipt** [cybercat-mods/HWG#29]
Im getting this error. https://mclo.gs/ZWIvLfs (-- the entire log. If u have discord i would prefer to talk with u by that way, mine is Shiplipt#5280 

[21:36:35] [Worker-Main-9/ERROR]: Couldn't load tag bewitchment:silver_tools as it is missing following references: hwg:silvergun (from Happiness is a Warm Gun),hwg:silver_bullet (from Happiness is a Warm Gun),hwg:shellhorse_revolver (from Happiness is a Warm Gun),hwg:silverbullets (from Happiness is a Warm Gun)
--
159 | [21:36:37] [Worker-Main-12/ERROR]: Parsing error loading recipe hwg:silverbullet
160 | com.google.gson.JsonSyntaxException: Unknown item 'bewitchment:silver_nugget'
161 | at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
162 | at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
163 | at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
164 | at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[intermediary-server.jar:?]
165 | at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
166 | at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.getComponents(GunTableRecipe.java:183) ~[HWGMod-1.17-1.0.12.jar:?]
167 | at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.read(GunTableRecipe.java:106) ~[HWGMod-1.17-1.0.12.jar:?]
168 | at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.method_8121(GunTableRecipe.java:100) ~[HWGMod-1.17-1.0.12.jar:?]
169 | at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
170 | at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
171 | at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
172 | at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
173 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
174 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
175 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
176 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
177 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
178 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
179 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
180 | at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
181 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
182 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
183 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
184 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
185 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
186 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
187 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
188 | at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
189 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
190 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
191 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
192 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
193 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
194 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
195 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
196 | at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
197 | at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
198 | at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
199 | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) [?:?]
200 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?]
201 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
202 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
203 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
204 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
205 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
206 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
207 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
208 | [21:36:37] [Worker-Main-12/ERROR]: Parsing error loading recipe hwg:hwg_book
209 | com.google.gson.JsonSyntaxException: Unknown item 'patchouli:guide_book'
210 | at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
211 | at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
212 | at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
213 | at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
214 | at net.minecraft.class_1867$class_1868.method_8142(class_1867.java:90) ~[intermediary-server.jar:?]
215 | at net.minecraft.class_1867$class_1868.method_8121(class_1867.java:79) ~[intermediary-server.jar:?]
216 | at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
217 | at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
218 | at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
219 | at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
220 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
221 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
222 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
223 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
224 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
225 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
226 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
227 | at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
228 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
229 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
230 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
231 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
232 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
233 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
234 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
235 | at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
236 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
237 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
238 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
239 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
240 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
241 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
242 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
243 | at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
244 | at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
245 | at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
246 | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) [?:?]
247 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?]
248 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
249 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
250 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
251 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
252 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
253 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
254 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
255 | [21:36:37] [Worker-Main-12/ERROR]: Parsing error loading recipe hwg:silvergun
256 | com.google.gson.JsonSyntaxException: Unknown item 'bewitchment:silver_ingot'
257 | at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
258 | at java.util.Optional.orElseThrow(Unknown Source) ~[?:?]
259 | at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
260 | at net.minecraft.class_1856.method_8107(class_1856.java:160) ~[intermediary-server.jar:?]
261 | at net.minecraft.class_1856.method_8102(class_1856.java:143) ~[intermediary-server.jar:?]
262 | at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.getComponents(GunTableRecipe.java:183) ~[HWGMod-1.17-1.0.12.jar:?]
263 | at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.read(GunTableRecipe.java:106) ~[HWGMod-1.17-1.0.12.jar:?]
264 | at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.method_8121(GunTableRecipe.java:100) ~[HWGMod-1.17-1.0.12.jar:?]
265 | at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
266 | at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
267 | at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
268 | at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
269 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
270 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
271 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
272 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
273 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
274 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
275 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
276 | at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
277 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
278 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
279 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
280 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
281 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
282 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
283 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
284 | at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
285 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
286 | at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
287 | at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
288 | at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
289 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
290 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
291 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
292 | at java.util.concurrent.CompletableFuture.complete(Unknown Source) ~[?:?]
293 | at net.minecraft.class_4014$1.method_18374(class_4014.java:53) ~[intermediary-server.jar:?]
294 | at net.minecraft.class_4014$1.method_18352(class_4014.java:50) ~[intermediary-server.jar:?]
295 | at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) [?:?]
296 | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) [?:?]
297 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
298 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
299 | at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
300 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
301 | at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
302 | at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
303 | at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]

**Comment by AzureDoom** [comment]
It's nothing and can be ignored, it's an optional thing if Bewitchment is installed along side HWG

**Comment by milkev** [comment]
i have bewitchment installed and i am still getting this error
![image](https://user-images.githubusercontent.com/22010128/134597201-9b3afe83-4eca-47a3-879f-199118a9a0d1.png)
this line is all that comes up in the log, though. none of the other stuff.

Additionally (because of this maybe?) there is no items in hwg with silver in the name or namespace

**Comment by milkev** [comment]
[https://github.com/AzureDoom/HWG/compare/1.17...milkev:patch-1](https://github.com/AzureDoom/HWG/compare/1.17...milkev:patch-1)
