### ISSUE TITLE
(Crash) Shot a werewolf with the silver hellhorse, the bullet was on fire and set fire and poisoned the werewolf.

### ISSUE THREAD

**Issue by TheRebelT** [cybercat-mods/HWG#3]
Also I was in creative mode if that helps.
Mods:
bewitchment-1.16.5-5
cloth-config-411.14-fabric
fabric-api-0.30.0+1.16
geckolib-fabric-1.16.5-3.0.23
HWGMod-1.16.5-1.0.4
Impersonate-2.1.0
Patchouli-1.16.4-50-FABRIC
Pehkui-1.8.0+21w08b
RoughlyEnoughItems-5.9.1
somnus-fabric-0.0.11-1.16.5
trinkets-2.6.7

Crash Log: https://pastebin.com/k4r13KHB
(Incase if it helps) Log: https://pastebin.com/n7RYDQ7A

**Comment by AzureDoom** [comment]
Was this client or server?

**Comment by TheRebelT** [comment]
The crash file said server so I assume it's a server issue

**Comment by AzureDoom** [comment]
fixed in latest
