### ISSUE TITLE
Incompatible with "Curses!" mod

### ISSUE THREAD

**Issue by DJMessy240** [cybercat-mods/HWG#32]
Thought I'd just give a quick heads up in case someone encounters this same issue.
When "Curses!" and HWG is loaded into the same game, reloading with any HWG gun makes all bullets in the player's inventory disappear and does not load any new bullets into the gun. Cool mod though, I really love it.

"Curses!" Link:
https://www.curseforge.com/minecraft/mc-mods/curses

P.S. This is with the 1.17.1 version of HWG and "Curses!"

**Comment by AzureDoom** [comment]
Do you have any active curses?

**Comment by DJMessy240** [comment]
Not at the time of testing it. The mod simply being active caused the guns not to reload. They never had the curses on them and no curses were active to my knowledge.

**Comment by AzureDoom** [comment]
I'd suggest opening a ticket on there side as well, I don't see anything that be causing the issue honestly outside this issue https://github.com/HyperPigeon/Curses-/issues/2 though it looks like the mod author isn't maintaining that mod anymore.
