### ISSUE TITLE
[SUGGESTION] Ability to disable mobspawns/loot-tables

### ISSUE THREAD

**Issue by Alkiasan** [cybercat-mods/HWG#33]
Hi, I wish to use this mod on my server, and want to have the guns obtainable in my own custom ways instead of through the mobs/structures that the guns can spawn in. Is it possible to add a config option to disable the spawning for mobs, and a config option to remove the guns from the loot tables?

Setting spawn weight to 0 doesn't seem to disable the mobs completely, and there's no option for loot tables.

**Comment by AzureDoom** [comment]
Set the biomes to nothing and they shouldn't spawn. You can override the loot tables via a datapack setting them nothing, unless you are referring to the meanie guns which is handled in code due to how vanilla chests work.

**Comment by Alkiasan** [comment]
Thank you!
Unrelated, but I ran into a random hang when reloading a shotgun one time.
No crash, just log spam with:
Failed to create new sound handle
Maximum sound pool size 247 reached

I'm currently unable to reproduce, but i'll open a new issue report if I find anything!
