### ISSUE TITLE
HWG no work multiplayer

### ISSUE THREAD

**Issue by Skatter1** [cybercat-mods/HWG#34]
I'm working on a modded server and the HWG mod isn't working properly with no indication of what's going on. The mob eggs for the various ones (Technodemonds and merc/spy) don't spawn them and the guns, while having the indicator, do not damage anything/break blocks. Assistance would be appreciated

**Comment by AzureDoom** [comment]
Logs, versions, etc are required.

**Comment by Skatter1** [comment]
Version is 1.17.1, and the only thread in the logs about HWG is:

@Final field field_4050:Lnet/minecraft/class_310; in hwg.mixins.json:HeldItemRendererMixin should be final

Is there a seperate config that I need to access to enable it on a server?

**Comment by AzureDoom** [comment]
Can not produce, please make sure the server has the mod installed as well.
