### ISSUE TITLE
Is it possible to make the Balrog and Grenades break blocks like Rockets?

### ISSUE THREAD

**Issue by derkaenaz** [cybercat-mods/HWG#37]
Is there a way to make the Balrog and the grenades break blocks like the Rockets do? For extra satisfaction with the Physics mod

**Comment by AzureDoom** [comment]
Yeah, I guess I can a config option for it.

**Comment by derkaenaz** [comment]
Excellent, thanks so much! Fantastic mod, great sounds and a playful balance between over-simplified and over-complicated gun mods HIGHLY RECOMMENDED to anybody reading

**Comment by AzureDoom** [comment]
This helped expose a bug with Rocket configs as well so that was also fixed 👍🏻
