### ISSUE TITLE
[BUG] Reloading a gun in creative mode causes game to freeze

### ISSUE THREAD

**Issue by GhostMic** [cybercat-mods/HWG#38]
You can recreate the problem by emptying a gun in survival and then reloading it with bullets in creative mode. This causes the game to freeze.

**Comment by AzureDoom** [comment]
What version are you on because that was patch ages ago to not reload at all.

**Comment by GhostMic** [comment]
I'm on the 1.17.1 version. I was using this file [HWGMod-1.17-1.0.22.jar].

**Comment by AzureDoom** [comment]
Fixed in latest version
