### ISSUE TITLE
No documentation on how to reload or resources needed for guns.

### ISSUE THREAD

**Issue by Pherex** [cybercat-mods/HWG#39]
I have a Meanie Gun and I've been able to craft the three ammo types aside from the flare and they won't reload the gun.

There should be some sort of documentation somewhere on the more unique aspects of the mod.

Using the latest version for 1.17

**Comment by AzureDoom** [comment]
I'll add tooltips.

**Comment by AzureDoom** [comment]
Added a tool tip in the latest version.
