### ISSUE TITLE
Meanie Gun 2 does not reload with redstone in inventory

### ISSUE THREAD

**Issue by Pherex** [cybercat-mods/HWG#40]
Meanie Gun 1 reloads, but not Meanie Gun 2.

Had two stacks of redstone in inventory and hotbar.

even made a redstone block just to make sure.

**Comment by AzureDoom** [comment]
Is this with the newest version?

**Comment by Pherex** [comment]
It is the newest version to my knowledge.

**Comment by AzureDoom** [comment]
try the new latest.
