### ISSUE TITLE
[21w44a] Gun Table GUI issue

### ISSUE THREAD

**Issue by kwpugh** [cybercat-mods/HWG#41]
The GUI is messed up, see pic.
![Screen Shot 2021-11-10 at 10 02 02 AM](https://user-images.githubusercontent.com/8809210/141148505-ed0f1dd1-8c83-42d9-9df7-d46c6a3dc96d.png)

**Comment by AzureDoom** [comment]
The mod is currently built against 21w43a but I will update and check here soon.

**Comment by AzureDoom** [comment]
Huh so it seems they flipped the height and width in the background drawing. Weird as hell to do but a patch is releasing here in a few minutes

![2021-11-10_12 05 42](https://user-images.githubusercontent.com/7415711/141159311-7f1e95a8-6308-4cce-a6ee-693ee02a6b38.png)
