### ISSUE TITLE
[1.18.1] Suggestion: projectile visual corrections and sniper rifle accuracy

### ISSUE THREAD

**Issue by Dyshonored** [cybercat-mods/HWG#42]
The bullet spread of the sniper rifle is quite noticeable when scoped in (and they are not facing the right direction when fired, a visual bug also present on the rocket launcher projectiles)

https://user-images.githubusercontent.com/61769878/146872941-d6af1e74-cb28-49ba-bc16-1d5f6cf9d3f4.mp4

.

**Comment by AzureDoom** [comment]
1. Spread is intended 
2. Geckolib Visual bug, not fixable

**Comment by Dyshonored** [comment]
It's alright, after playing for some time I've gotten used to the mod now
