### ISSUE TITLE
Game won't start when mod is enabled

### ISSUE THREAD

**Issue by VinDaCaterer** [cybercat-mods/HWG#45]
Sodium, fabric api, and gecko lib are the only other mods. Full crash report below:
[crash-2022-01-13_18.44.34-client.txt](https://github.com/AzureDoom/HWG/files/7866854/crash-2022-01-13_18.44.34-client.txt)

**Comment by AzureDoom** [comment]
Cloth config is clearly marked on CurseForge

**Comment by AzureDoom** [comment]
![Screenshot_20220113-203343_Chrome](https://user-images.githubusercontent.com/7415711/149436209-b289f688-5ccc-4247-a47a-9c250e9eae03.jpg)

**Comment by VinDaCaterer** [comment]
thanks bro, maybe add a banner like for fabric api and gecko lib on curseforge.

**Comment by AzureDoom** [comment]
I don't feel that I should have to idiot proof something that is already clearly marked.
