### ISSUE TITLE
Game Crashes When Generating A New World (HWGMod-1.18.2-1.1.0.jar)

### ISSUE THREAD

**Issue by MinicomSoftware** [cybercat-mods/HWG#52]
Here is the crash report:
[crash-2022-03-08_16.28.11-client.txt](https://github.com/cybercat-mods/HWG/files/8210672/crash-2022-03-08_16.28.11-client.txt)

Here is what I have installed:
![001](https://user-images.githubusercontent.com/29552915/157349248-82cd14b9-62c2-43c7-94d4-3bfb80ecf9b6.PNG)

No other mods besides Fabric. I will try a different version.

**Comment by MinicomSoftware** [comment]
Maybe I'm using 1.18.1 for the 1.18.2 which leads to NoSuchMethodError because it's calling a deprecated method. I just clicked the orange "install" button on curseforge and it set this all up for me. That's one way to replicate the error.

**Comment by AzureDoom** [comment]
1.18.2 doesn't support 1.18.1.
