### ISSUE TITLE
Mod Doesnt Work in 1.18.2

### ISSUE THREAD

**Issue by JibberishGulp** [cybercat-mods/HWG#54]
I am using the newest versions of  farbic api (0.47.8) , geckolib (3.0.35) and HWGMOD-1.18.2-1.1.4 and minecraft crashes whenever I start it. I am using no other mods and I get this error code:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hwg'!
Exit Code: -1

Ive included the full crash report below:

[crash report.txt](https://github.com/cybercat-mods/HWG/files/8356143/crash.report.txt)

**Comment by AzureDoom** [comment]
Take a look at the required libraries.
