### ISSUE TITLE
Most of the bullets from Merc and Demons stuck in air

### ISSUE THREAD

**Issue by HacoKavanah** [cybercat-mods/HWG#56]
![2022-04-03_16 42 52](https://user-images.githubusercontent.com/87395651/161430955-4321b40f-edd1-4017-9c2e-26ed1ef57f52.png)

**Comment by AzureDoom** [comment]
version please

**Comment by HacoKavanah** [comment]
oh sorry, its HWGMod-1.18.2-1.1.4.jar
