### ISSUE TITLE
Gun firing animations bug when multiple guns of the same type are present

### ISSUE THREAD

**Issue by elidhan** [cybercat-mods/HWG#60]
Issue:
When having two or more of the same gun in a player's hotbar, the animations will not play when firing unless it's the first gun in the hotbar.

How to recreate:
Have two or more of the same guns in the hotbar.

**Comment by AzureDoom** [comment]
Minecraft/mod version please.

**Comment by elidhan** [comment]
Version 1.1.5 for Minecraft 1.18.2

**Comment by AzureDoom** [comment]
This is a Geckolib bug and won't be resolved until the rewrite of 1.19
