### ISSUE TITLE
ammo entities stuck in air

### ISSUE THREAD

**Issue by Helioux** [cybercat-mods/HWG#61]
Found that if you shoot bullets and/or fireballs from the blazerod gun into the air, the ammo will be stuck in the air... Forever. There is no way to get rid of them, entity clearing did not affect the fireballs and restarting the server/client did nothing either, at this point it's causing way too much lag in and around our base.

**Comment by Helioux** [comment]
This is in the most recent release version 1.18.2

**Comment by AzureDoom** [comment]
you can do /kill hwg:entity

**Comment by Helioux** [comment]
We keep getting the error that says: 

Expected whitespace to end one argument, but found trailing data
 /kill hwg:entity <--- [HERE]

When we attempt to run that command

**Comment by AzureDoom** [comment]
you need to change it for the entity you wish to kill

**Comment by Helioux** [comment]
Is there a list somewhere to find actual entity names?

**Comment by AzureDoom** [comment]
Update please

**Comment by Helioux** [comment]
thanks man
Lmao, sorry didn't mean to annoy you enough to have to push an update.

**Comment by AzureDoom** [comment]
It's been needing fixed. Just been busy with work
