### ISSUE TITLE
The mod can't run.

### ISSUE THREAD

**Issue by GeneralSniper** [cybercat-mods/HWG#67]
I went to test the mod yesterday and today and I changed the Quilted Fabric and Geckolib versions, but it still didn't work, it always appears that I need the latest version of Geckolib, but even so, it doesn't work.I went to test the mod yesterday and today and I changed the Quilted Fabric and Geckolib versions, but it still didn't work, it always appears that I need the latest version of Geckolib, but even so, it doesn't work..

![image](https://user-images.githubusercontent.com/86884479/185999944-37a7b167-f2a6-4cbb-9fdb-271dac01f461.png)
![image](https://user-images.githubusercontent.com/86884479/185999958-ada161e9-59cf-4b76-8777-36a4bd248d38.png)

**Comment by AzureDoom** [comment]
Why are you using Quilt if you are using Fabric.
