### ISSUE TITLE
Game crashes when crafting too many bullets

### ISSUE THREAD

**Issue by gittibene** [cybercat-mods/HWG#75]
[crash-2023-01-17_22.57.41-client.txt](https://github.com/cybercat-mods/HWG/files/10439728/crash-2023-01-17_22.57.41-client.txt)

Also please add a way to automate bullet production, maybe with create? Thanks for your awesome mod though

**Comment by Jiroga** [comment]
Can confirm, I can replicate this issue consistently when right-clicking to pick up bullets from the gun table if the mouse is holding an amount of bullets that I cannot fully pick up (i.e. holding 60 bullets and attempting to pick up the next 10 causes a crash). The crash also happens even without holding anything, though this has only been tested with Sniper Rounds.

Fabric version: 1.19.2 (0.14.12)
Mod version: HWGMod-1.19.2-1.2.10
Dependency: geckolib-fabric-1.19-3.1.38
Crash Log: https://mclo.gs/5CNn8iv

**Comment by AzureDoom** [comment]
I am only updating 1.19.3 at this time

**Comment by Jiroga** [comment]
Unfortunate, but understandable.


> [crash-2023-01-17_22.57.41-client.txt](https://github.com/cybercat-mods/HWG/files/10439728/crash-2023-01-17_22.57.41-client.txt)
> 
> Also please add a way to automate bullet production, maybe with create? Thanks for your awesome mod though

A good way to go about it would be to install Crafttweaker if you are the server owner and scripting your own recipes for bullets and other items you wish to automate. Create automatically adds crafting table recipes to its shapeless crafting API, which would allow you to automate bullets.

**Comment by gittibene** [comment]
Thank you, that's exactly what i ended up doing! Works fine
