### ISSUE TITLE
Reloading Luger causes crash 

### ISSUE THREAD

**Issue by ObieTheWitchBoy** [cybercat-mods/HWG#76]
When reloading the Luger (not tested with other guns) in HWGMod-1.19.2-1.2.10 with Immersive Portals also installed, it crashes and sends the player to this screen. 

![image](https://user-images.githubusercontent.com/53503648/224435056-da3864ac-44a2-448b-9999-b87578867d04.png)

**Comment by AzureDoom** [comment]
this is an issue with Immersive Portals side.
