### ISSUE TITLE
Crashing with lithium-fabric-mc1.19.2-0.11.1 

### ISSUE THREAD

**Issue by CantWeAllDisagree** [cybercat-mods/HWG#79]
https://paste.atlauncher.com/view/b7a7aad0-dd8b-4f24-ba0a-61eceb63b4bc 

Tested with multiple versions, quilt HWG 1.2.11 works. Newer versions crash but are marked fabric/quilt.

**Comment by AzureDoom** [comment]
Please ensure you are using the latest SmartBrainLib
