### ISSUE TITLE
Gunsmith not working

### ISSUE THREAD

**Issue by srnyx** [cybercat-mods/HWG#8]
Right-clicking Gun Smith does nothing it shakes its head and makes hrmmm sound.

**Comment by AzureDoom** [comment]
No log = no help. Its like pointing in the direction of your car and going "it no work"

**Comment by srnyx** [comment]
> No log = no help. Its like pointing in the direction of your car and going "it no work"

https://paste.gg/p/srnyx/26b3822341184f8f8a955f2789d0eb4f

**Comment by AzureDoom** [comment]
I see no issues besides your server lagging.

**Comment by srnyx** [comment]
Here's a list of all my mods: https://github.com/Haven-King/TinyTweaks/issues/74#issuecomment-809678817

**Comment by AzureDoom** [comment]
again, that log does not state any issues with this mod.

**Comment by srnyx** [comment]
> again, that log does not state any issues with this mod.

So then, why isn't the gunsmith working?
_Also, I was not relating this issue to the TinyTweaks one, I was just linking the list of my mods._

**Comment by AzureDoom** [comment]
It's working fine in both dev and production for me. Your log doesn't state any issues, therefore, I can only conclude another mod is messing with villagers and the mod itself is fine as again, it's working in dev and production for myself.
