### ISSUE TITLE
Inconsistent I-frame and knockback on mobs

### ISSUE THREAD

**Issue by Cirvel** [cybercat-mods/HWG#82]
Mobs being shot at close range frequently receive knockback and I-frame that blocks damage from further incoming bullets, unlike at longer ranges where such effects barely happen.
This is noticeable when using fully automatic weapons which are also the most affected by it.

Version: [1.4.6](https://www.curseforge.com/minecraft/mc-mods/happiness-is-a-warm-gun/files/4498729)

**Comment by AzureDoom** [comment]
This is due to the change of hit scan to entity projectiles. The only fix would be to use hit scan only which breaks on shooting up or long distances or just the projectiles again. It was chosen to keep the mix.

**Comment by Cirvel** [comment]
Looks like I'm gonna be sticking with the minigun now as it does not suffer from this, but thanks for the explanation though!
