### ISSUE TITLE
Incompatible with Optifine / Optifabric Mods

### ISSUE THREAD

**Issue by JustSomeGuyFromMC** [cybercat-mods/HWG#85]
This issue occurs with HWG, Azure Lib, and SmartBrainLib. But the main issue is that while the game loads, it fails to render due to the error code listed below...
 - The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.setSampler(int, Object)" because "shaderinstance" is null

**Comment by AzureDoom** [comment]
Don't use Optifine, use Sodium and Iris. Optifine is closed sourced ARR
