### ISSUE TITLE
Flamethrower produces bullet items when used against a wall at point blank range.

### ISSUE THREAD

**Issue by BowBoy1** [cybercat-mods/HWG#86]
Was messing around with the mod in 1.19.2 and found that when using a flamethrower against a wall when the player is against said wall, bullet items are rapidly produced.

**Comment by AzureDoom** [comment]
Screenshot what you mean please?

**Comment by BowBoy1** [comment]
here you go
![Screenshot_1](https://github.com/cybercat-mods/HWG/assets/93287836/651f6021-d5cb-4151-a2d9-1dd143dc4d03)
![Screenshot_2](https://github.com/cybercat-mods/HWG/assets/93287836/5c9d95b9-30c2-4a05-8fef-0e4c0a083bc1)
![Screenshot_3](https://github.com/cybercat-mods/HWG/assets/93287836/9224945d-ee6e-485e-9ec1-3f3518cb3393)
