### ISSUE TITLE
Silver Pistol doesn't reload while the silver bullets are in inventory HWG 1.19.2

### ISSUE THREAD

**Issue by AntonioPufferino** [cybercat-mods/HWG#87]
Self-explanatory, I crafted a Silver pistol and emptied it to double check to see if the right bullets will load in and they didn't, i pressed the reload keybind and it refuses to reload even with the appropriate ammo.

**Comment by AzureDoom** [comment]
Can you please confirm the version of the mod and Minecraft you are on?

**Comment by AntonioPufferino** [comment]
Sure thing, the version of HWG that's being used is Ver. 1.2.9 and the minecraft version is 1.19.2

**Comment by AzureDoom** [comment]
Closing as per discord with cyber, that version is super super outdated.
