### ISSUE TITLE
the mod doesnt properly work

### ISSUE THREAD

**Issue by Aabaddon** [cybercat-mods/HWG#88]
it doesnt crash, it just doesnt shoot bullets, each time i try to use any gun its like the gun disappears and appears instanly again like it resets or something and doesnt shoot anything

**Comment by AzureDoom** [comment]
Logs and version. Working fine for me in my mods

**Comment by Aabaddon** [comment]
[latest.log](https://github.com/cybercat-mods/HWG/files/11874876/latest.log)

minecraft 1.19.2 fabric 0.14.21

hwg 1.4.10

**Comment by somekindofanimal** [comment]
I'm encountering the same issue.  Same mod version and game version.  Weapons won't fire at all.

**Comment by AzureDoom** [comment]
Unable to reproduce using the latest version on CurseForge now for 1.19.2.

**Comment by somekindofanimal** [comment]
Not sure if this will help anyone, but I went through and have figured out that the issue is with the Gliders mod.  For some reason, it causes HWG weapons not to shoot

**Comment by Sunconure11** [comment]
@somekindofanimal Is this the mod in question?

https://modrinth.com/mod/gliders

**Comment by somekindofanimal** [comment]
Yes, that's the one

**Comment by Sunconure11** [comment]
@somekindofanimal Can you post your mod list? I want to look at it. The latest fix did not seem to solve the issue.

**Comment by somekindofanimal** [comment]
My mod list:
[Mine.txt](https://github.com/cybercat-mods/HWG/files/12165584/Mine.txt)

**Comment by somekindofanimal** [comment]
Also here is another mod list that was having the same issue, which I cross-referenced with mine to determine that Gliders was the issue:
[His.txt](https://github.com/cybercat-mods/HWG/files/12165603/His.txt)

**Comment by jwaxy** [comment]
I am having the same issue. Is there any fixes?
