### ISSUE TITLE
Internal Exception Error with gun table recipe

### ISSUE THREAD

**Issue by DabossxX** [cybercat-mods/HWG#89]
On latest patch (1.20) with all required dependencies up to date, this error message shows when server attempts to boot.

Connection Lost
Internal Exception: ionetty.handler codec. Decoder: Exception: jamalang.IllegalArgumentEception: Unknoun recipe serializer huggun_table

Server cannot even be started

**Comment by AzureDoom** [comment]
Server is starting fine on 1.20.1.
