### ISSUE TITLE
please... dont list your mod as forge compatible if it uses sinatra connector

### ISSUE THREAD

**Issue by walksanatora** [cybercat-mods/HWG#93]
by that logic 90% of fabric mods should be called forge mods
and that is not very nice since any bug in the "forge" version could be either a bug in connector *or* your mod which can make debugging a pain

**Comment by AzureDoom** [comment]
It's perfectly valid to mark as forge with connector as the mod works perfectly on it to make easier for pack authors to add it to Forge packs ready to go.

**Comment by walksanatora** [comment]
not when i tried in 1.20.1

**Comment by walksanatora** [comment]
unless it is somehow incompatible with minecolonies/ one of it's dependicies

**Comment by AzureDoom** [comment]
It's likely Minecolonies as I'm using my this mod and my other Fabric Connector marked mods fine in my own 1.20.1 modpack.
