### ISSUE TITLE
Forge compability

### ISSUE THREAD

**Issue by inmourning** [cybercat-mods/HWG#95]
HWG is listed as compatible with forge through connector. However, it requires smartbrainlib, which doesn't work on forge 47.1.3... and connector needs forge 47.1.3.

**Comment by AzureDoom** [comment]
First read the patch notes of that SBL version you are using, then downgrade since you read the note and enjoy the mod.

**Comment by inmourning** [comment]
yes i just realised i have made a complete fool of myself

fast answer nice
