### ISSUE TITLE
Change of gun's ammo capacity?

### ISSUE THREAD

**Issue by Felixvillas** [cybercat-mods/HWG#96]
Hello~
I have installed this mod in my Minecraft. I have found some attributes that I can configure, like gun damage. However, I couldn't find the configuration option for the ammo capacity.
Could I change the ammo capacity of each gun? If possible, how can I do it?

**Comment by AzureDoom** [comment]
If you are on 1.20.1, that's the cap config for each gun. Only 1.20.1+ will have those configurations.
