### ISSUE TITLE
java.lang.NoSuchFieldError: TICKING_LIGHT_BLOCK

### ISSUE THREAD

**Issue by UDP415** [cybercat-mods/HWG#97]
Game starts, world loads, trying to shoot a gun results in a crash, and the world can't be reopened. I assume there's a problem with the bullet entity, or I might've messed up the version of one of the mods, but the dependencies added by default crash the game on startup.
using:
forge 47.1.3
azurelib-forge-1.20.1-1.0.33
SmartBrainLib-neoforge-1.20.1-1.12
Connector-1.0.0-beta.19+1.20.1-full
fabric-api-0.90.0+1.9.26+1.20.1
[crash-2023-10-21_16.01.21-client.txt](https://github.com/cybercat-mods/HWG/files/13061740/crash-2023-10-21_16.01.21-client.txt)
[crash-2023-10-21_16.01.21-server.txt](https://github.com/cybercat-mods/HWG/files/13061741/crash-2023-10-21_16.01.21-server.txt)

**Comment by AzureDoom** [comment]
Update both this and AzureLib
