### ISSUE TITLE
Game Crash Trying To Load Mod

### ISSUE THREAD

**Issue by Bropugfect** [cybercat-mods/HWG#98]
On the cursedforge app 

The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class dev.su5ed.sinytra.connector.mod.compat.fieldtypes.RedirectingIdMapper overrides final method net.minecraft.core.IdMapper.m_7942_(I)Ljava/lang/Object;

**Comment by AzureDoom** [comment]
This would be an issue with the connector mod. Needs reported to it's repo.
