### ISSUE TITLE
Getting RuntimeException error (Exit Code: -1)

### ISSUE THREAD

**Issue by ghost** [cybercat-mods/HWG#99]
The game crashed whilst rendering overlay
Error: java.lang.RuntimeException: java.lang.ExceptionInInitializerError

**Comment by AzureDoom** [comment]
You have to post an extra log.

**Comment by ghost** [comment]
Is this mod meant to be played with other mods? Also when I drag the connector file into the mod folder it creates a connector folder which is unusual. I think that might be the issue, but i'm not sure.

**Comment by AzureDoom** [comment]
Why wouldn't be meant to be played with others? That is fine for connector, but without a proper log I am closing this.
